version: "3.2"
services:
  database:
    container_name: officetel-container
    image: mysql:8.0.22
    volumes:
      - ~/docker/mysql/officetel/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mysql/officetel/var/lib/mysql:/var/lib/mysql
      - ~/docker/mysql/officetel/var/log/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=officeteldb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    ports:
      - "3310:3306"
    networks:
      - test_env
  application:
    container_name: officetel-application-container
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://officetel-container:3306/officeteldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - test_env



networks:
  test_env:
    driver: bridge